<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_content']['pct_image_crop_data'][0] = '';
$GLOBALS['TL_LANG']['tl_content']['pct_image_crop_data'][1] = '';
$GLOBALS['TL_LANG']['tl_content']['pct_image_crop_legend'] = 'Bildbeschnitt-Einstellungen';