<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MSC']['pct_image_crop'] = 'PCT Image Crop';
$GLOBALS['TL_LANG']['MSC']['free'] = 'Frei';
$GLOBALS['TL_LANG']['MSC']['16_9'] = '16:9';
$GLOBALS['TL_LANG']['MSC']['4_3'] = '4:3';
$GLOBALS['TL_LANG']['MSC']['1_1'] = '1:1';

// ratios
$GLOBALS['TL_LANG']['PCT_IMAGE_CROP']['buttons']['free'] 	= 'Free';
$GLOBALS['TL_LANG']['PCT_IMAGE_CROP']['buttons']['16_9'] 	= '16:9';
$GLOBALS['TL_LANG']['PCT_IMAGE_CROP']['buttons']['4_3']	 	= '4:3';
$GLOBALS['TL_LANG']['PCT_IMAGE_CROP']['buttons']['1_1']	 	= '1:1';